### PR TITLE
Fix combine harakat with text bug

### PR DESCRIPTION
**Pull request by AliOsm**
There are some bugs in the code when combining the harakat with text, I've fixed them.

### CODE REVIEW

**Comment by Barqawiz** [comment]
Thanks for your contribution @AliOsm to find the bug, if I am not mistaken you added this line, right? 

`if haraka == '<UNK>' or haraka == "ـ":`

There are many format differences (spaces) make it hard to identify the changes exactly.

Can you download the code again and make another pull request with only the code changes (without formatting the files)? **will accept it directly**

**Comment by AliOsm** [comment]
Sure, I will do it ASAP.
Another thing, what is the data used to train this model?
Thank you.

**Comment by Barqawiz** [comment]
I used data from this source: https://sourceforge.net/projects/tashkeela/

**Comment by AliOsm** [comment]
There is another thing you can update it in the model, why you set the maximum number of characters to 315? you can handle an unknown number of characters, this will make your model predict very long sentences and take context from them, it is better than split the long sentences then feed them to the model.

**Comment by Barqawiz** [comment]
The reason following line used to combine  ّ _  with the previous character if used as a connector:
```
harakat_stack = Stack()
```

Because the network might predict one of the following output cases on one character input:
- one haraka like  َ _  OR
-  one haraka like  ّ _ OR
- two haraka like  ّ  َ  _   ّ ِ  _   ّ  ُ _ OR
- nothing

and there is no indication whether the network decides to predict 0 or 1 or 2 haraka 

This combine code can be enhanced because it takes into consideration when the extra  ّ _ used on space and some other cases should be taken into consideration

however, your commit helped me to identify that this line committed by mistake and should be removed:
`temp_stack    = Stack()`

**Comment by AliOsm** [comment]
I think after my commit you don't need any stacks again, I've returned the diacritics from `logits_to_text` method as a list, so they don't overlap and can be added to the original text without any problem.

**Comment by Barqawiz** [comment]
@AliOsm yes you are right about the sentence size, the shorter the easier for the network to predict. 
It was for experiment reasons to build a model that able to predict the longest possible sentence.

For the majority of cases, a shorter number like 100 or 150 would be easier for the network as you mentioned.

Update: will work a version with less output size as you suggested

**Comment by Barqawiz** [comment]
The issue with the committed code it does not take the connector scenario in consideration 

When ّ_ used with previous haraka on the same character

**Comment by AliOsm** [comment]
Exactly the contrary, the old code doesn't take into account this case and distributes the `ّ ` and the other diacritic used with it over the characters after it.
The committed code returns the diacritics into a list and solves the problem, so for example if the sentence was:
`هذا الصبي`
It should be diacritized as follows:
`هَذَا الصَّبِيُّ`
But, the old code outputs:
`هَذَا الصَبّيِ`
While the committed code outputs:
`هَذَا الصَّبِيُّ`

This happens because the old code returns the following string:
`ــــَُِّّ`
While the committed code returns the following list:
`['َ', 'َ', 'ـ', 'ـ', 'ـ', 'ـ', 'َّ', 'ِ', 'ُّ']`

The difference is clear and you can try everything yourself.

Note: Take the Arabic words and diacritics to something like notepad or sublime text to see the difference clearly.

**Comment by Barqawiz** [comment]
OK the mistake is returning it as text not list, the change in (Shakkala.py) made it clear now so no need for the stack thing.

**Comment by Barqawiz** [comment]
The code merged and your name @AliOsm  added to the readme file as a contributor:
https://github.com/Barqawiz/Shakkala#contributors

Thanks for the fix, when you mentioned the other file fix (return list) it becomes clear where is the bug because it is not live chat without refresh did not check this earlier comment :)

> I think after my commit you don't need any stacks again, I've returned the diacritics from `logits_to_text` method as a list, so they don't overlap and can be added to the original text without any problem.

**Comment by AliOsm** [comment]
Can you mention how you had split Tashkeela dataset? and if it is possible publish the training/validation/testing datasets files?
Thank you

**Comment by Barqawiz** [comment]
The dataset full of long historical sentences with different ways or schools of diacritics, it took me many iterations to check which part of data influence a wrong prediction then remove it from the training set then retrain again.

About validation try to include modern sentences to avoid historical data overfitting.

Planning to publish a notebook about data processing and training when possible.

**Pull request merged**
